easy_admin:
   entities:
       # List the entity class name you want to manage
       - App\Entity\Recettes
       - App\Entity\Avis
       - App\Entity\Categorie
       - App\Entity\Etapes
       - App\Entity\Ingredient
       - App\Entity\Unite
       - App\Entity\Ustensiles