easy_admin:
   entities:
       # List the entity class name you want to manage
       - App\Entity\Recipes
       - App\Entity\Reviews
       - App\Entity\Tag
       - App\Entity\Steps
       - App\Entity\Ingredients
       - App\Entity\Unity
       - App\Entity\CookingTools